version: "3"

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5000:5000"

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  peerjs:
    image: peerjs/peerjs-server
    ports:
      - "9000:9000"
