version: "3.7"

services:
  server:
    build:
      target: production
      context: ./server
      dockerfile: Dockerfile
    expose:
      - "8000"
    ports:
      - "8000:8000"
    command: node build/server.js
  peerjs:
    image: peerjs/peerjs-server
